<a id='top'></a>
# Links #
* [Top](#top)
* [x] [3](#3)
* [x] [4](#4)
* [x] [5](#5)
* [x] [6](#6)
* [x] [8](#8)
* [x] [14](#14)
* [x] [15](#15)

In [1]:
import numpy as np
import math as ma

<a id='3'></a>
# 3 - Done #
The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143?

In [36]:
sympy.isprime(5)

True

In [103]:
def prime_fac_loop(n):
    n_orig = n
    fac = [1]
    for i in range(2, n_orig):
        div = n / i
        if (div == int(div)):
            div = int(div)
            if (sympy.isprime(i)):
                fac.append(i)
            if (sympy.isprime(div)):
                fac.append(div)
#             print(fac)
            n = div
            prod = np.prod(np.array(fac))
#             print(prod)
            if (prod == n_orig or n == 1):
                return max(fac)

In [105]:
prime_fac_loop(13195)

29

In [106]:
prime_fac_loop(600851475143)

6857

<a id='4'></a>

# 4 - 11/10/20 #

A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of two 3-digit numbers.

In [2]:
def is_palindrome(n):
    n = str(int(n))
    for i in range(ma.floor(len(n) / 2)):
        if n[i] != n[len(n) - i - 1]:
            return False
    return True

In [9]:
is_palindrome(101)

True

In [12]:
pals = []
for i in range(900, 1000):
    for j in range(900, 1000):
        if is_palindrome(i*j):
            pals.append(i*j)

print(pals)
print(max(pals))

[819918, 824428, 819918, 906609, 824428, 886688, 861168, 888888, 861168, 888888, 886688, 906609]
906609


<a id='5'></a>
# 5 - Done #
2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

In [44]:
def lcm_first_n(n):
    '''Gets the least common multiple of the first n integers, [1,n] inclusive.
    
    Multiples the highest power of each prime form 1 to n to get lcm. 
    Uses sympy to find each prime number from 1 to n. 
    Takes the log of each number from 1 to n with base of that prime p.
    Multiples all p^floor of max value of log_p([1,n]) to get result.
    '''
    nums = np.arange(1,n+1)
    result = 1
    for i in range(1,n+1):
        if sympy.isprime(i):
            result = result * (i ** np.floor(np.max(np.log(nums) / np.log(i))))
    return result

In [45]:
lcm_first_n(20)

232792560.0

<a id='6'></a>

# 6 - Done #

The sum of the squares of the first ten natural numbers is,

The square of the sum of the first ten natural numbers is,

Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is .

Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

In [56]:
nums = np.arange(1,11)
nums_sq = nums**2
(np.sum(nums))**2 - np.sum(nums_sq)

2640

In [14]:
nums = np.arange(1,101)
nums_sq = nums**2
(np.sum(nums))**2 - np.sum(nums_sq)

25164150

<a id='8'></a>

# 8 - 11/18/20#
Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?

In [34]:
nums_str = \
'73167176531330624919225119674426574742355349194934\
96983520312774506326239578318016984801869478851843\
85861560789112949495459501737958331952853208805511\
12540698747158523863050715693290963295227443043557\
66896648950445244523161731856403098711121722383113\
62229893423380308135336276614282806444486645238749\
30358907296290491560440772390713810515859307960866\
70172427121883998797908792274921901699720888093776\
65727333001053367881220235421809751254540594752243\
52584907711670556013604839586446706324415722155397\
53697817977846174064955149290862569321978468622482\
83972241375657056057490261407972968652414535100474\
82166370484403199890008895243450658541227588666881\
16427171479924442928230863465674813919123162824586\
17866458359124566529476545682848912883142607690042\
24219022671055626321111109370544217506941658960408\
07198403850962455444362981230987879927244284909188\
84580156166097919133875499200524063689912560717606\
05886116467109405077541002256983155200055935729725\
71636269561882670428252483600823257530420752963450'

nums = np.array([int(num) for num in nums_str], dtype=np.int64)

max_prod = 1

for i in range(len(nums)):
    box = nums[i:(i + 13)]
    prod = np.prod(box)
    
    if prod > max_prod:
        max_prod = prod
        print(box, i, prod)
        
print(max_prod)

[7 3 1 6 7 1 7 6 5 3 1 3 3] 0 5000940
[4 9 1 9 2 2 5 1 1 9 6 7 4] 16 9797760
[9 2 2 5 1 1 9 6 7 4 4 2 6] 19 13063680
[2 5 1 1 9 6 7 4 4 2 6 5 7] 21 25401600
[5 1 1 9 6 7 4 4 2 6 5 7 4] 22 50803200
[1 1 9 6 7 4 4 2 6 5 7 4 7] 23 71124480
[1 9 6 7 4 4 2 6 5 7 4 7 4] 24 284497920
[9 6 7 4 4 2 6 5 7 4 7 4 2] 25 568995840
[5 3 4 9 1 9 4 9 3 4 9 6 9] 40 1020366720
[3 4 9 1 9 4 9 3 4 9 6 9 8] 41 1632586752
[9 1 9 4 9 3 4 9 6 9 8 3 5] 43 2040733440
[8 6 9 4 7 8 8 5 1 8 4 3 8] 88 2972712960
[4 3 5 5 7 6 6 8 9 6 6 4 8] 195 6270566400
[3 5 5 7 6 6 8 9 6 6 4 8 9] 196 14108774400
[5 5 7 6 6 8 9 6 6 4 8 9 5] 197 23514624000
23514624000


<a id='14'></a>
# 14 - Done #
The following iterative sequence is defined for the set of positive integers:

n → n/2 (n is even)
n → 3n + 1 (n is odd)

Using the rule above and starting with 13, we generate the following sequence:

13 → 40 → 20 → 10 → 5 → 16 → 8 → 4 → 2 → 1
It can be seen that this sequence (starting at 13 and finishing at 1) contains 10 terms. Although it has not been proved yet (Collatz Problem), it is thought that all starting numbers finish at 1.

Which starting number, under one million, produces the longest chain?

NOTE: Once the chain starts the terms are allowed to go above one million.

In [98]:
def next_collatz(n):
    '''Returns next integer according to rules of the collatz sequence.'''
    if n % 2 == 0:
        return n / 2
    else:
        return 3*n + 1

def collatz_length(n):
    '''Returns the length of the collatz sequence starting from n and ending at 1.'''
    i = 0
    while n != 1:
        n = next_collatz(n)
        i += 1
    return i

In [96]:
def longest_collatz(n):
    '''Returns a tuple including the integer from [2,n) 
    which has the longest collatz sequence and the length of that sequence.
    If there is more than 1 integer with the same length collatz sequence, 
    the largest one is returned.  
    '''
    
    nums = np.arange(2, int(n), dtype=np.int64)
    while np.sum(nums==1) < nums.size - 2:
        mods = nums % 2
        non_one = nums != 1
        nums[mods == 0] = nums[mods == 0] / 2
        nums[non_one * (mods == 1)] = 3 * nums[non_one * (mods == 1)] + 1
    
    candidates = np.argwhere(nums != 1) + 2
#     print(candidates)
    lengths = []
    for candidate in candidates:
        lengths.append(collatz_length(candidate))
#     print(lengths)
    if all(element == lengths[0] for element in lengths):
        return (candidates[-1, 0], lengths[-1])
        
    return (candidates[np.argmax(lengths), 0], lengths[np.argmax(lengths)])

In [97]:
longest_collatz(10**6)

(837799, 524)

<a id='15'></a>
# 15 #
Starting in the top left corner of a 2×2 grid, and only being able to move to the right and down, there are exactly 6 routes to the bottom right corner.

How many such routes are there through a 20×20 grid?

In [5]:
import scipy.special
import random

In [66]:
def lattice_paths(s):
    '''Returns the number of lattice paths from the top left to 
    bottom right of a square of side length s, using only right and downward moves.
    
    There are a total 2s moves required in all paths.
    For the first s moves, there are a total of 2**s possible choices.
    There is 1=comb(s,0) choice with all right moves. This imples only 1 way to fill the remaining s moves, all down.
    There are s=comb(s,1) choices with 1 right moves and s-1 down. There are now s ways to fill the remaining moves with s-1 rights and 1 down.
    There are comb(s, 2) with 2 rights moves. There are comb(s,2) ways to fill the remainig s-2 rights and 2 downs
    And so on.
    
    To get the total number of paths, square the results 
    of each line since there are comb(s,i) ways to independently ]
    choose the first s moves and another comb(s,i) ways to choose the next: 
    1**2 + s**2 + comb(s,2)**2 + ... comb(s,s)**2
    '''
    
    sum = 0
    for i in range(s+1):
        sum += (scipy.special.comb(s,i))**2
    return sum

In [65]:
lattice_paths(20)

137846528820.0