<a id='top'></a>
# Links #
* [Top](#top)
* [x] [3](#3)
* [x] [4](#4)
* [x] [5](#5)
* [x] [6](#6)
* [x] [8](#8)
* [x] [13](#13)
* [x] [14](#14)
* [x] [15](#15)
* [x] [46](#46)
* [ ] [54](#54)

In [1]:
import numpy as np
import math as ma
import pandas as pd

<a id='3'></a>
# 3 - Done #
The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143?

In [36]:
sympy.isprime(5)

True

In [103]:
def prime_fac_loop(n):
    n_orig = n
    fac = [1]
    for i in range(2, n_orig):
        div = n / i
        if (div == int(div)):
            div = int(div)
            if (sympy.isprime(i)):
                fac.append(i)
            if (sympy.isprime(div)):
                fac.append(div)
#             print(fac)
            n = div
            prod = np.prod(np.array(fac))
#             print(prod)
            if (prod == n_orig or n == 1):
                return max(fac)

In [105]:
prime_fac_loop(13195)

29

In [106]:
prime_fac_loop(600851475143)

6857

<a id='4'></a>

# 4 - 11/10/20 #

A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of two 3-digit numbers.

In [2]:
def is_palindrome(n):
    n = str(int(n))
    for i in range(ma.floor(len(n) / 2)):
        if n[i] != n[len(n) - i - 1]:
            return False
    return True

In [9]:
is_palindrome(101)

True

In [12]:
pals = []
for i in range(900, 1000):
    for j in range(900, 1000):
        if is_palindrome(i*j):
            pals.append(i*j)

print(pals)
print(max(pals))

[819918, 824428, 819918, 906609, 824428, 886688, 861168, 888888, 861168, 888888, 886688, 906609]
906609


<a id='5'></a>
# 5 - Done #
2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

In [44]:
def lcm_first_n(n):
    '''Gets the least common multiple of the first n integers, [1,n] inclusive.
    
    Multiples the highest power of each prime form 1 to n to get lcm. 
    Uses sympy to find each prime number from 1 to n. 
    Takes the log of each number from 1 to n with base of that prime p.
    Multiples all p^floor of max value of log_p([1,n]) to get result.
    '''
    nums = np.arange(1,n+1)
    result = 1
    for i in range(1,n+1):
        if sympy.isprime(i):
            result = result * (i ** np.floor(np.max(np.log(nums) / np.log(i))))
    return result

In [45]:
lcm_first_n(20)

232792560.0

<a id='6'></a>

# 6 - Done #

The sum of the squares of the first ten natural numbers is,

The square of the sum of the first ten natural numbers is,

Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is .

Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

In [56]:
nums = np.arange(1,11)
nums_sq = nums**2
(np.sum(nums))**2 - np.sum(nums_sq)

2640

In [14]:
nums = np.arange(1,101)
nums_sq = nums**2
(np.sum(nums))**2 - np.sum(nums_sq)

25164150

# 7 - 11/26/20#
10,001st prime

In [7]:
primes = [2]

for i in range(3, 10**12):
    mods = i % np.array(primes)
    if np.all(mods != 0):
        primes.append(i)
    if len(primes) >= 10001:
        break
        
print(primes[10000])

104743


In [11]:
print(primes[-1])

104743


<a id='8'></a>

# 8 - 11/18/20#
Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?

In [34]:
nums_str = \
'73167176531330624919225119674426574742355349194934\
96983520312774506326239578318016984801869478851843\
85861560789112949495459501737958331952853208805511\
12540698747158523863050715693290963295227443043557\
66896648950445244523161731856403098711121722383113\
62229893423380308135336276614282806444486645238749\
30358907296290491560440772390713810515859307960866\
70172427121883998797908792274921901699720888093776\
65727333001053367881220235421809751254540594752243\
52584907711670556013604839586446706324415722155397\
53697817977846174064955149290862569321978468622482\
83972241375657056057490261407972968652414535100474\
82166370484403199890008895243450658541227588666881\
16427171479924442928230863465674813919123162824586\
17866458359124566529476545682848912883142607690042\
24219022671055626321111109370544217506941658960408\
07198403850962455444362981230987879927244284909188\
84580156166097919133875499200524063689912560717606\
05886116467109405077541002256983155200055935729725\
71636269561882670428252483600823257530420752963450'

nums = np.array([int(num) for num in nums_str], dtype=np.int64)

max_prod = 1

for i in range(len(nums)):
    box = nums[i:(i + 13)]
    prod = np.prod(box)
    
    if prod > max_prod:
        max_prod = prod
        print(box, i, prod)
        
print(max_prod)

[7 3 1 6 7 1 7 6 5 3 1 3 3] 0 5000940
[4 9 1 9 2 2 5 1 1 9 6 7 4] 16 9797760
[9 2 2 5 1 1 9 6 7 4 4 2 6] 19 13063680
[2 5 1 1 9 6 7 4 4 2 6 5 7] 21 25401600
[5 1 1 9 6 7 4 4 2 6 5 7 4] 22 50803200
[1 1 9 6 7 4 4 2 6 5 7 4 7] 23 71124480
[1 9 6 7 4 4 2 6 5 7 4 7 4] 24 284497920
[9 6 7 4 4 2 6 5 7 4 7 4 2] 25 568995840
[5 3 4 9 1 9 4 9 3 4 9 6 9] 40 1020366720
[3 4 9 1 9 4 9 3 4 9 6 9 8] 41 1632586752
[9 1 9 4 9 3 4 9 6 9 8 3 5] 43 2040733440
[8 6 9 4 7 8 8 5 1 8 4 3 8] 88 2972712960
[4 3 5 5 7 6 6 8 9 6 6 4 8] 195 6270566400
[3 5 5 7 6 6 8 9 6 6 4 8 9] 196 14108774400
[5 5 7 6 6 8 9 6 6 4 8 9 5] 197 23514624000
23514624000


<a id='13'></a>

# 13 - 11/23/20 #
Work out the first ten digits of the sum of the following one-hundred 50-digit numbers.

In [2]:
nums_str = \
'37107287533902102798797998220837590246510135740250\
46376937677490009712648124896970078050417018260538\
74324986199524741059474233309513058123726617309629\
91942213363574161572522430563301811072406154908250\
23067588207539346171171980310421047513778063246676\
89261670696623633820136378418383684178734361726757\
28112879812849979408065481931592621691275889832738\
44274228917432520321923589422876796487670272189318\
47451445736001306439091167216856844588711603153276\
70386486105843025439939619828917593665686757934951\
62176457141856560629502157223196586755079324193331\
64906352462741904929101432445813822663347944758178\
92575867718337217661963751590579239728245598838407\
58203565325359399008402633568948830189458628227828\
80181199384826282014278194139940567587151170094390\
35398664372827112653829987240784473053190104293586\
86515506006295864861532075273371959191420517255829\
71693888707715466499115593487603532921714970056938\
54370070576826684624621495650076471787294438377604\
53282654108756828443191190634694037855217779295145\
36123272525000296071075082563815656710885258350721\
45876576172410976447339110607218265236877223636045\
17423706905851860660448207621209813287860733969412\
81142660418086830619328460811191061556940512689692\
51934325451728388641918047049293215058642563049483\
62467221648435076201727918039944693004732956340691\
15732444386908125794514089057706229429197107928209\
55037687525678773091862540744969844508330393682126\
18336384825330154686196124348767681297534375946515\
80386287592878490201521685554828717201219257766954\
78182833757993103614740356856449095527097864797581\
16726320100436897842553539920931837441497806860984\
48403098129077791799088218795327364475675590848030\
87086987551392711854517078544161852424320693150332\
59959406895756536782107074926966537676326235447210\
69793950679652694742597709739166693763042633987085\
41052684708299085211399427365734116182760315001271\
65378607361501080857009149939512557028198746004375\
35829035317434717326932123578154982629742552737307\
94953759765105305946966067683156574377167401875275\
88902802571733229619176668713819931811048770190271\
25267680276078003013678680992525463401061632866526\
36270218540497705585629946580636237993140746255962\
24074486908231174977792365466257246923322810917141\
91430288197103288597806669760892938638285025333403\
34413065578016127815921815005561868836468420090470\
23053081172816430487623791969842487255036638784583\
11487696932154902810424020138335124462181441773470\
63783299490636259666498587618221225225512486764533\
67720186971698544312419572409913959008952310058822\
95548255300263520781532296796249481641953868218774\
76085327132285723110424803456124867697064507995236\
37774242535411291684276865538926205024910326572967\
23701913275725675285653248258265463092207058596522\
29798860272258331913126375147341994889534765745501\
18495701454879288984856827726077713721403798879715\
38298203783031473527721580348144513491373226651381\
34829543829199918180278916522431027392251122869539\
40957953066405232632538044100059654939159879593635\
29746152185502371307642255121183693803580388584903\
41698116222072977186158236678424689157993532961922\
62467957194401269043877107275048102390895523597457\
23189706772547915061505504953922979530901129967519\
86188088225875314529584099251203829009407770775672\
11306739708304724483816533873502340845647058077308\
82959174767140363198008187129011875491310547126581\
97623331044818386269515456334926366572897563400500\
42846280183517070527831839425882145521227251250327\
55121603546981200581762165212827652751691296897789\
32238195734329339946437501907836945765883352399886\
75506164965184775180738168837861091527357929701337\
62177842752192623401942399639168044983993173312731\
32924185707147349566916674687634660915035914677504\
99518671430235219628894890102423325116913619626622\
73267460800591547471830798392868535206946944540724\
76841822524674417161514036427982273348055556214818\
97142617910342598647204516893989422179826088076852\
87783646182799346313767754307809363333018982642090\
10848802521674670883215120185883543223812876952786\
71329612474782464538636993009049310363619763878039\
62184073572399794223406235393808339651327408011116\
66627891981488087797941876876144230030984490851411\
60661826293682836764744779239180335110989069790714\
85786944089552990653640447425576083659976645795096\
66024396409905389607120198219976047599490197230297\
64913982680032973156037120041377903785566085089252\
16730939319872750275468906903707539413042652315011\
94809377245048795150954100921645863754710598436791\
78639167021187492431995700641917969777599028300699\
15368713711936614952811305876380278410754449733078\
40789923115535562561142322423255033685442488917353\
44889911501440648020369068063960672322193204149535\
41503128880339536053299340368006977710650566631954\
81234880673210146739058568557934581403627822703280\
82616570773948327592232845941706525094512325230608\
22918802058777319719839450180888072429661980811197\
77158542502016545090413245809786882778948721859617\
72107838435069186155435662884062257473692284509516\
20849603980134001723930671666823555245252804609722\
53503534226472524250874054075591789781264330331690'

In [62]:
# Find sum of each place value (one's place, 10's place, etc.)
# Put this sum mod 10 in for the digit of the final sum of all digits
# Carry the remaining digits of the sum onto the next iteration
# For last iteraion, take entire sum, including carries

In [61]:
digits = np.array([int(num) for num in nums_str], dtype=np.float64)
carry = 0
sum_digits = []

for i in range(49, -1, -1):
    place_val = digits[list(range(i, 5000, 50))]
#     print(place_val)
    digit_sum = np.sum(place_val) + carry
    this_digit = digit_sum % 10
    carry = ma.trunc(digit_sum / 10)
    if i != 0:
        sum_digits.append(this_digit)
    else:
        sum_digits.append(digit_sum)

#     print(digit_sum, carry, i)
#     print(this_digit, 49-i)

print(sum_digits[::-1])

[553, 7, 3, 7, 6, 2, 3, 0, 3, 9, 0, 8, 7, 6, 6, 3, 7, 3, 0, 2, 0, 4, 8, 7, 4, 6, 8, 3, 2, 9, 8, 5, 9, 7, 1, 7, 7, 3, 6, 5, 9, 8, 3, 1, 8, 9, 2, 6, 7, 2]


<a id='14'></a>
# 14 - Done #
The following iterative sequence is defined for the set of positive integers:

n → n/2 (n is even)
n → 3n + 1 (n is odd)

Using the rule above and starting with 13, we generate the following sequence:

13 → 40 → 20 → 10 → 5 → 16 → 8 → 4 → 2 → 1
It can be seen that this sequence (starting at 13 and finishing at 1) contains 10 terms. Although it has not been proved yet (Collatz Problem), it is thought that all starting numbers finish at 1.

Which starting number, under one million, produces the longest chain?

NOTE: Once the chain starts the terms are allowed to go above one million.

In [98]:
def next_collatz(n):
    '''Returns next integer according to rules of the collatz sequence.'''
    if n % 2 == 0:
        return n / 2
    else:
        return 3*n + 1

def collatz_length(n):
    '''Returns the length of the collatz sequence starting from n and ending at 1.'''
    i = 0
    while n != 1:
        n = next_collatz(n)
        i += 1
    return i

In [96]:
def longest_collatz(n):
    '''Returns a tuple including the integer from [2,n) 
    which has the longest collatz sequence and the length of that sequence.
    If there is more than 1 integer with the same length collatz sequence, 
    the largest one is returned.  
    '''
    
    nums = np.arange(2, int(n), dtype=np.int64)
    while np.sum(nums==1) < nums.size - 2:
        mods = nums % 2
        non_one = nums != 1
        nums[mods == 0] = nums[mods == 0] / 2
        nums[non_one * (mods == 1)] = 3 * nums[non_one * (mods == 1)] + 1
    
    candidates = np.argwhere(nums != 1) + 2
#     print(candidates)
    lengths = []
    for candidate in candidates:
        lengths.append(collatz_length(candidate))
#     print(lengths)
    if all(element == lengths[0] for element in lengths):
        return (candidates[-1, 0], lengths[-1])
        
    return (candidates[np.argmax(lengths), 0], lengths[np.argmax(lengths)])

In [97]:
longest_collatz(10**6)

(837799, 524)

<a id='15'></a>
# 15 #
Starting in the top left corner of a 2×2 grid, and only being able to move to the right and down, there are exactly 6 routes to the bottom right corner.

How many such routes are there through a 20×20 grid?

In [5]:
import scipy.special
import random

In [66]:
def lattice_paths(s):
    '''Returns the number of lattice paths from the top left to 
    bottom right of a square of side length s, using only right and downward moves.
    
    There are a total 2s moves required in all paths.
    For the first s moves, there are a total of 2**s possible choices.
    There is 1=comb(s,0) choice with all right moves. This imples only 1 way to fill the remaining s moves, all down.
    There are s=comb(s,1) choices with 1 right moves and s-1 down. There are now s ways to fill the remaining moves with s-1 rights and 1 down.
    There are comb(s, 2) with 2 rights moves. There are comb(s,2) ways to fill the remainig s-2 rights and 2 downs
    And so on.
    
    To get the total number of paths, square the results 
    of each line since there are comb(s,i) ways to independently ]
    choose the first s moves and another comb(s,i) ways to choose the next: 
    1**2 + s**2 + comb(s,2)**2 + ... comb(s,s)**2
    '''
    
    sum = 0
    for i in range(s+1):
        sum += (scipy.special.comb(s,i))**2
    return sum

In [65]:
lattice_paths(20)

137846528820.0

<a id='46'></a>

# 46 - 4/1/2021 #

It was proposed by Christian Goldbach that every odd composite number can be written as the sum of a prime and twice a square.

9 = 7 + 2×1**2

15 = 7 + 2×2**2

It turns out that the conjecture was false.

What is the smallest odd composite that cannot be written as the sum of a prime and twice a square?It was proposed by Christian Goldbach that every odd composite number can be written as the sum of a prime and twice a square.

Find a number, $n$ s.t. $(n - 2k^2)$ is not prime for all $k < \sqrt{\frac{n}{2}}$

In [2]:
import sympy as sy

In [86]:
testNum = 10**4 # number of odd numbers to test

maxK = ma.floor(np.sqrt(testNum / 2)) # largest value of k for the entire set of n
k = np.arange(maxK + 1, dtype=np.int64)
k = 2 * (k ** 2)

p = np.array([i for i in sy.primerange(1, testNum+1)], dtype=np.int64) # all primes less than the largest value of n

for n in range(3, testNum, 2):
    test = n - k
    if not np.any(np.isin(test, p)):
        print(n)
#         for i in test:
#             if(i > 0):
#                 print(i, sy.primefactors(i))
        break
print('done')

5777
done


<a id="54"></a>

# 54 #
In the card game poker, a hand consists of five cards and are ranked, from lowest to highest, in the following way:

High Card: Highest value card.

One Pair: Two cards of the same value.

Two Pairs: Two different pairs.

Three of a Kind: Three cards of the same value.

Straight: All cards are consecutive values.

Flush: All cards of the same suit.

Full House: Three of a kind and a pair.

Four of a Kind: Four cards of the same value.

Straight Flush: All cards are consecutive values of same suit.

Royal Flush: Ten, Jack, Queen, King, Ace, in same suit.

The cards are valued in the order:

2, 3, 4, 5, 6, 7, 8, 9, 10, Jack, Queen, King, Ace.

If two players have the same ranked hands then the rank made up of the highest value wins; for example, a pair of eights beats a pair of fives (see example 1 below). But if two ranks tie, for example, both players have a pair of queens, then highest cards in each hand are compared (see example 4 below); if the highest cards tie then the next highest cards are compared, and so on.

How many hands does Player 1 win?

In [12]:
import re

In [59]:
with open("p54-poker.txt", "r") as f:
    text = f.read()
    f.close()
# print(text)
# print(re.findall(r"(\w{2}\s+){4}\w{2}", text))
print(re.findall(r"(?:\w{2}\s+){4}\w{2}", text))

['8C TS KC 9H 4S', '7D 2S 5D 3S AC', '5C AD 5D AC 9C', '7C 5H 8D TD KS', '3H 7H 6S KC JS', 'QH TD JC 2D 8S', 'TH 8H 5C QS TC', '9H 4D JC KS JS', '7C 5H KC QH JD', 'AS KH 4C AD 4S', '5H KS 9C 7D 9H', '8D 3S 5D 5C AH', '6H 4H 5C 3H 2H', '3S QH 5S 6S AS', 'TD 8C 4H 7C TC', 'KC 4C 3H 7S KS', '7C 9C 6D KD 3H', '4C QS QC AC KH', 'JC 6S 5H 2H 2D', 'KD 9D 7C AS JS', 'AD QH TH 9D 8H', 'TS 6D 3S AS AC', '2H 4S 5C 5S TC', 'KC JD 6C TS 3C', 'QD AS 6H JS 2C', '3D 9H KC 4H 8S', 'KD 8S 9S 7C 2S', '3S 6D 6S 4H KC', '3C 8C 2D 7D 4D', '9S 4S QH 4H JD', '8C KC 7S TC 2D', 'TS 8H QD AC 5C', '3D KH QD 6C 6S', 'AD AS 8H 2H QS', '6S 8D 4C 8S 6C', 'QH TC 6D 7D 9D', '2S 8D 8C 4C TS', '9S 9D 9C AC 3D', '3C QS 2S 4H JH', '3D 2D TD 8S 9H', '5H QS 8S 6D 3C', '8C JD AS 7H 7D', '6H TD 9D AS JH', '6C QC 9S KD JC', 'AH 8S QS 4D TH', 'AC TS 3C 3D 5C', '5S 4D JS 3D 8H', '6C TS 3S AD 8C', '6D 7C 5D 5H 3S', '5C JC 2H 5S 3D', '5H 6H 2S KS 3D', '5D JD 7H JS 8H', 'KH 4H AS JS QS', 'QC TC 6D 7C KS', '3D QS TS 2H JS', '4D AS 9S

In [67]:
display(pd.read_csv("p54-poker.txt", sep=" ", names=[0,1,2,3,4,5,6,7,8,9]))

0   1   2   3   4   5   6   7   8   9
0    8C  TS  KC  9H  4S  7D  2S  5D  3S  AC
1    5C  AD  5D  AC  9C  7C  5H  8D  TD  KS
2    3H  7H  6S  KC  JS  QH  TD  JC  2D  8S
3    TH  8H  5C  QS  TC  9H  4D  JC  KS  JS
4    7C  5H  KC  QH  JD  AS  KH  4C  AD  4S
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
995  3S  AD  9H  JC  6D  JD  AS  KH  6S  JH
996  AD  3D  TS  KS  7H  JH  2D  JS  QD  AC
997  9C  JD  7C  6D  TC  6H  6C  JC  3D  3S
998  QC  KC  3S  JC  KD  2C  8D  AH  QS  TS
999  AS  KD  3D  JD  8H  7C  8C  5C  QD  6C

[1000 rows x 10 columns]

In [ ]:
class Hand:
    """Holds the 5 cards which make up a poker hand.
    
    Attributes
    cards -- list of 5 strings, each string being a card in the form {value}{suit}
    highCard -- the highest value card
    """
    
    def __init__(self, cards=None):
        if cards is not None:
            self.cards = 
            for card in cards:
                
        
    def compare(self, Hand):
        